### ISSUE TITLE
About Me typo, "warm"ing people to not email you.

### ISSUE THREAD

**Issue by techtolentino** [Snugug/blog#23]
Hey @Snugug 

(It's Randy -- hope all is well).

Since I don't have Twitter, I couldn't DM you and I wanted to say hi. You also `warm` readers to not email you, so I figured I file an issue on your blog 😉 

`If you must email me... but I will warm you there's a strong...`

Anyway, my original message was to thank you for your Lighthouse post. I ran an audit on something I did recently and man oh man, I am ashamed!

Anyway, thank you.

Also, can I get a thumbs-up for 1) following your contact instructions and 2) a pretty witty use of GitHub issues?

Keep up the great work brother!

**Comment by Snugug** [comment]
Hey Randy! Great to hear from you!

I'm glad you found it useful! 

If you'd like, the source for that page is https://github.com/Snugug/blog/blob/master/pages/me.md; feel free to file a PR to fix it!

**Comment by Snugug** [comment]
Resolved by #24
